export enum MenuTab {
  BASIC_PERSON = "BASIC_PERSON",
  NATURAL_PERSON = "NATURAL_PERSON",
  ADDRESS = "ADDRESS",
  CONTACT = "CONTACT",
  BANK_INFO = "BANK_INFO",
  // EMAIL = "EMAIL",
  // WORK_INFO = "WORK_INFO",
  // MOVABLE_ASSETS = "MOVABLE_ASSETS",
  // IMMOVABLE_ASSETS = "IMMOVABLE_ASSETS",
  // REFERENCES = "REFERENCES",
  FATCA = "FATCA",
}

export enum PersonType {
  PF = "pf",
  PJ = "pj",
}
